In [1]:
pip install opencv-python --user

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install opencv-python==4.6.0.66


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 MB 477.7 kB/s eta 0:00:0000:0100:03
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.7.0.68
    Uninstalling opencv-python-4.7.0.68:
      Successfully uninstalled opencv-python-4.7.0.68
Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2

In [3]:
import os

import numpy as np
import cv2

alg="haarcascade_frontalface_default.xml" 
haar_cascade=cv2.CascadeClassifier(alg)  
dataset="datasets"  #making a folder in which our train data is captured
# sub_data="rudra"
# path=os.path.join(dataset,sub_data)
# if not os.path.isdir(path):
#     os.mkdir(path)
(width,height)=(130,100)

cam=cv2.VideoCapture(0)
(image,label,name,id)=([],[],{},0)  #making emptyy folders
for (subdir,dir,file) in os.walk(dataset):    #it iterate over datasets and assigh names
    for i in dir:
        name[id]=i
        new_path=os.path.join(dataset,i) #join attach the 2 path and make a new path dir or pwd
        for x in os.listdir(new_path):
            new_new_path=new_path + '/' + str(x)  #iterating over images by giving path
            N=id #id initilize to n and n use as int in label
            image.append(cv2.imread(new_new_path,0))
            label.append(int(N))
        id+=1
(image,label)=[np.array(arr) for arr in [image,label]]
print(image,label)
model=cv2.face.FisherFaceRecognizer_create()
model.train(image,label)


#count=0
while True:
    #print(count)
    (_,img)=cam.read()
    
    grayimg=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=haar_cascade.detectMultiScale(grayimg,1.3,4)
    for x,y,w,h in face:

        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
        slice_face=grayimg[y:y+h ,x:x+w]
        face_resize=cv2.resize(slice_face,(width,height))
        #cv2.imwrite("%s/%s.png" % (path,count),face_resize)
        #count+=1
        prediction=(model.predict(face_resize))
        if prediction[1]<800:
            org=(0,185)
            
            cv2.putText(img,'%s-%s.0f'%(name[prediction[0]],prediction[1]),(x-10,y-10),cv2.FONT_HERSHEY_SIMPLEX,2,(255,255,0))
            print((prediction[0]))
        else:
             print('no img')
        

        

        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

        
    cv2.imshow("face_detection",img)


    key=cv2.waitKey(10)
    if key==27:
        break
cam.release()
cv2.destroyAllWindows()



[[[ 30  32  32 ...  45  41  32]
  [ 33  36  49 ...  42  32  27]
  [ 44  37  38 ...  31  24  29]
  ...
  [108 101  90 ...  30  33  29]
  [101 101 106 ...  31  24  26]
  [ 99  87  99 ...  28  30  30]]

 [[ 22  31  38 ...  50  48  44]
  [ 35  39  45 ...  47  51  40]
  [ 51  52  47 ...  50  45  33]
  ...
  [ 94  99  85 ...  22  25  33]
  [105 103  90 ...  32  32  34]
  [ 98  97  93 ...  28  27  35]]

 [[ 44  48  53 ...  43  42  42]
  [ 43  39  52 ...  46  42  40]
  [ 32  39  34 ...  39  44  37]
  ...
  [106 104  97 ...  25  23  19]
  [108 109  99 ...  24  24  29]
  [ 98 105 108 ...  22  21  21]]

 ...

 [[ 75  76  78 ...  59  56  52]
  [ 81  70  74 ...  52  61  60]
  [ 71  77  72 ...  61  65  59]
  ...
  [116 127 136 ...  26  34  28]
  [112 117 129 ...  32  29  31]
  [102  99 103 ...  28  33  26]]

 [[ 88  74  88 ...  57  63  61]
  [ 84  87  81 ...  54  63  61]
  [ 80  89  83 ...  57  58  65]
  ...
  [ 30  30  27 ...  33  31  36]
  [ 31  32  30 ...  29  30  32]
  [ 28  33  24 ...  35  34  